"""'second'

Revision ID: 78838e5e3bb8
Revises: 9a4064d2363e
Create Date: 2023-03-21 23:20:46.816106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78838e5e3bb8'
down_revision = '9a4064d2363e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('rate history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_name', sa.String(length=50), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('date_rec', sa.String(length=120), nullable=True),
    sa.Column('time_rec', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_coin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('user_selections')
    op.drop_table('rate history')
    op.drop_table('coins')
    # ### end Alembic commands ###
